#define AKey SDL_SCANCODE_A
#define DKey SDL_SCANCODE_D
#define SKey SDL_SCANCODE_S
#define WKey SDL_SCANCODE_W
#define SPACEBAR SDL_SCANCODE_SPACE

#define CHARACTER_WIDTH 85
#define CHARACTER_HEIGHT 115
#define SPRITE_HORIZONTAL 120
#define SPRITE_VERTICAL 130

#define SPRITE_NO 3
#define UP_SPRITE_NO 1
#define MOVING_SPRITE_NO 10

#define LEVEL_WIDTH 4800
#define LEVEL_HEIGHT 4000